Bump version to 0.10.6, check dir, add exits

diff --git a/qemu.SlackBuild b/qemu.SlackBuild
--- a/qemu.SlackBuild
+++ b/qemu.SlackBuild
@@ -1,36 +1,55 @@
 #!/bin/sh
 #
-# SlackBuild for qemu
+# SlackBuild for Qemu
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
 #
 
-. /etc/slack-package.conf
+. ../slack-package.conf
 
 NAME=qemu
-VERSION=0.10.1
+VERSION=0.10.6
 BUILD=1
+ARCH=${ARCH:-i486}
 
-cd $TMP
-tar -zxvf $CWD/$NAME-$VERSION.tar.gz
+TMP=${TMP:-/tmp}
+CWD=${CWD:-`pwd`}
+PKG_DIR=${PKG_DIR:-/tmp}
+
+if [ ! -e $TMP ]; then
+  mkdir -p $TMP # location to build the source
+fi
+
 SRC=$TMP/$NAME-$VERSION
+if [ -e $SRC -a -d $SRC ]; then
+  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  exit 1
+fi
+
+PKG=$TMP/package-$NAME
+if [ -e $PKG -a -d $PKG ]; then
+  echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
+  exit 2
+fi
+mkdir -p $PKG
+
+# Extract and fix source
+cd $TMP
+tar xzvf $CWD/$NAME-$VERSION.tar.gz
 cd $SRC
 fix_source
 
+# Configure
 CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --prefix=/usr \
             --audio-drv-list=oss,alsa,sdl,esd \
             --audio-card-list=ac97,es1370,sb16,cs4231a,adlib,gus \
             --enable-mixemu \
-            --enable-sparse \
             --enable-system \
             --enable-linux-user || exit 1
 
-make || exit 2
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
+# Build & install
+make -j2 || exit 2
 make DESTDIR=$PKG \
      bindir=/bin \
      mandir=/usr/man \
@@ -38,6 +57,7 @@ make DESTDIR=$PKG \
      docdir=/usr/doc/$NAME-$VERSION \
      install || exit 3
 
+# Preapare
 bin_perms $PKG
 gzip_man $PKG
 create_docs $PKG $NAME-$VERSION
@@ -51,6 +71,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Pack
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.tgz
@@ -58,6 +79,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.tgz > $PKGNAME.tgz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
